using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace stock_api.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "Customers" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    "Name" character varying(120) NOT NULL,
                    "Email" character varying(254),
                    "Phone" character varying(40),
                    "CreatedAt" timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_Customers" PRIMARY KEY ("Id")
                );

                CREATE TABLE IF NOT EXISTS "Orders" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    "CustomerId" integer NOT NULL,
                    "Status" character varying(20) NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_Orders" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_Orders_Customers_CustomerId"
                        FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE RESTRICT
                );

                CREATE TABLE IF NOT EXISTS "OrderLineItems" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    "OrderId" integer NOT NULL,
                    "Name" character varying(160) NOT NULL,
                    "Quantity" integer NOT NULL,
                    "UnitPrice" numeric(12,2) NOT NULL,
                    CONSTRAINT "PK_OrderLineItems" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_OrderLineItems_Orders_OrderId"
                        FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS "IX_OrderLineItems_OrderId" ON "OrderLineItems" ("OrderId");
                CREATE INDEX IF NOT EXISTS "IX_Orders_CustomerId" ON "Orders" ("CustomerId");
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "OrderLineItems");

            migrationBuilder.DropTable(
                name: "Orders");

            migrationBuilder.DropTable(
                name: "Customers");
        }
    }
}
